In [85]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import fastai
import seaborn as sns 
import pandas as pd

import torch
import torch.nn as nn
from torch import tensor
from fastai.data.all import to_np


ModuleNotFoundError: No module named 'nn'

In [65]:
x = tensor([[1,2,3],[4,5,6]])
y = tensor([[7,8,9],[10,11,12]])
torch.cat([x,y])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [66]:
torch.cat([x,y], dim=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

In [67]:
z = tensor([[13,14,15]])
torch.cat([x,y, z])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [68]:
w = tensor([[16],[17]])
torch.cat([x,y, w], dim=1)

tensor([[ 1,  2,  3,  7,  8,  9, 16],
        [ 4,  5,  6, 10, 11, 12, 17]])

In [79]:
model = nn.Linear(4, 5)
model.weight, model.bias


(Parameter containing:
 tensor([[ 0.1321,  0.2911,  0.0731, -0.3915],
         [-0.4883, -0.0612, -0.3576,  0.4659],
         [-0.3364,  0.4563,  0.2662, -0.3554],
         [ 0.0711, -0.0323,  0.3143,  0.1223],
         [-0.0597,  0.1131,  0.2172,  0.0019]], requires_grad=True),
 Parameter containing:
 tensor([-0.3869,  0.2534,  0.3895, -0.4279, -0.3120], requires_grad=True))

In [83]:
w, b = model.parameters()
w,b

(Parameter containing:
 tensor([[ 0.1321,  0.2911,  0.0731, -0.3915],
         [-0.4883, -0.0612, -0.3576,  0.4659],
         [-0.3364,  0.4563,  0.2662, -0.3554],
         [ 0.0711, -0.0323,  0.3143,  0.1223],
         [-0.0597,  0.1131,  0.2172,  0.0019]], requires_grad=True),
 Parameter containing:
 tensor([-0.3869,  0.2534,  0.3895, -0.4279, -0.3120], requires_grad=True))

NameError: name 'plot_function' is not defined